version: '3.9'
services:

  redis-session-storage:
    image: redis:5.0.5
    container_name: redis-session-storage
    restart: unless-stopped

  api-selector-db:
    container_name: api-selector-db
    image: postgres:alpine
    env_file:
      - selector_db.example.env
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost",]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - "9000:5432"
  
  sector-api-db:
    container_name: sector-api-db
    image: postgres:alpine
    env_file:
      - sector-api_db.example.env
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost",]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - "9001:5432"
  
  history-api-db:
    container_name: history-api-db
    image: postgres:alpine
    env_file:
      - history-api_db.example.env
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost",]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - "9002:5432"

  nomenclature-api-db:
    container_name: nomenclature-api-db
    image: postgres:alpine
    env_file:
      - nomenclature-api_db.example.env
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost",]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - "9003:5432"

  client-api-db:
    container_name: client-api-db
    image: postgres:alpine
    env_file:
      - client-api_db.example.env
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost",]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - "9004:5432"