version: '3.9'
services:

  redis-session-storage:
    image: redis:5.0.5
    container_name: redis-session-storage
    restart: unless-stopped

  sector-api:
    build:
        context: ./sector_api/
        dockerfile: Dockerfile
    # env_file:
    #   - .docker.env
    command: python main.py
    restart:
      unless-stopped
    ports:
      - "8000:8081"
    depends_on:
      - sector-api-db
  
  sector-api-db:
    container_name: sector-api-db
    image: postgres:alpine
    env_file:
      - sector-api_db.example.env
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost",]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - "9001:5432"
  
  history-api:
    build:
        context: ./history_api/
        dockerfile: Dockerfile
    # env_file:
    #   - .docker.env
    command: python main.py
    restart:
      unless-stopped
    ports:
      - "8001:8081"
    depends_on:
      - history-api-db

  history-api-db:
    container_name: history-api-db
    image: postgres:alpine
    env_file:
      - history-api_db.example.env
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost",]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - "9002:5432"

  nomenclature-api:
    build:
        context: ./nomenclature_api/
        dockerfile: Dockerfile
    # env_file:
    #   - .docker.env
    command: python main.py
    restart:
      unless-stopped
    ports:
      - "8002:8081"
    depends_on:
      - nomenclature-api-db

  nomenclature-api-db:
    container_name: nomenclature-api-db
    image: postgres:alpine
    env_file:
      - nomenclature-api_db.example.env
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost",]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - "9003:5432"

  client-api:
    build:
        context: ./nomenclature_api/
        dockerfile: Dockerfile
    # env_file:
    #   - .docker.env
    command: python main.py
    restart:
      unless-stopped
    ports:
      - "8003:8081"
    depends_on:
      - client-api-db

  client-api-db:
    container_name: client-api-db
    image: postgres:alpine
    env_file:
      - client-api_db.example.env
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost",]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - "9004:5432"